export const factionList = [
  'Empire',
  'Dwarfs',
  'VampireCounts',
  'Greenskins',
  'WarriorsOfChaos',
  'Bretonnia',
  'Beastmen',
  'WoodElves',
  'Norsca',
  'HighElves',
  'DarkElves',
  'Lizardmen',
  'Skaven',
  'TombKings',
  'VampireCoast',
  'Kislev',
  'GrandCathay',
  'Khorne',
  'Nurgle',
  'Slaanesh',
  'Tzeentch',
  'OgreKingdoms',
  'DaemonsOfChaos',
] as const;
