import Head from 'next/head';

export default function Home() {
  return (
    <main className="container mx-auto">
      <Head>
        <title>TW3 Stats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>HOOOOOOME</h2>
    </main>
  );
}
