import Head from 'next/head';
import MatchupTable from '../components/MatchupTable';

export default function Home() {
  return (
    <main className="container mx-auto">
      <Head>
        <title>TW3 Stats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2 className="text-2xl mx-auto text-center my-8">Faction Winrates:</h2>
      <MatchupTable />
    </main>
  );
}
